theme: jekyll-theme-modernist
url: https://mesinkasir.github.io/cleanpos-opensource/

# Site settings
title: OPEN SOURCE POINT OF SALE POS free download aplikasi kasir pos gratis
email: hockeycorpmarketing@gmail.com.com
description: "Source code point of sale free donwload for wholesale and retail compleks with purchase - inventori stok - point of sale wholesale and retail - report detail."


social:
  - title: twitter
    url: https://twitter.com/hockeycomp
  - title: facebook
    url: https://www.facebook.com/mesinkasircomplete
  - title: instagram
    url: https://www.instagram.com/mesinkasircomplete/
  - title: youtube
    url: https://www.youtube.com/channel/UCIBWTgOXH5oa2YlbfpO7QLQ/featured
  - title: github
    url: https://github.com/mesinkasir/cleanpos-opensource
